require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'rnCallRecorder' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNCallKeep', :path => '../node_modules/react-native-callkeep'

  pod 'react-native-immediate-phone-call', :path => '../node_modules/react-native-immediate-phone-call'

  target 'rnCallRecorderTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'rnCallRecorder-tvOS' do
  # Pods for rnCallRecorder-tvOS

  target 'rnCallRecorder-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
